# Generated by Django 2.2.3 on 2019-07-20 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_auto_20190720_1849'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booleanquestionanswer',
            name='question_number',
        ),
        migrations.RemoveField(
            model_name='multiplechoicequestionanswer',
            name='question_number',
        ),
        migrations.RemoveField(
            model_name='theoryquestionanswer',
            name='question_number',
        ),
        migrations.AddField(
            model_name='booleanquestion',
            name='question_number',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='multiplechoicequestion',
            name='question_number',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='theoryquestion',
            name='question_number',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
